# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Dz0dTzSHjUp51o4qcf5TsQnQZSdklWCndWH2DFCyYxYHw/B6Vn96wtQm5YyXonQoEPaLXKYYE3lY1rF58cbwVNdkqlxUYtOCJPnr0agCDGNryPBnirYHaM8zPm4mX6OF4oS+InnEuC2wlVF6olz3gdvzXmYQWmI2So0RTlimOp1geaAzv5wYdvoR/5B9PZSLNCZFF6loYcucaU0DPWxy/aX70pedVnX/5VcoU+Dl2xyMX+PS9uykxx2iDYfZRv0VohIssA3MFJAmeGObQ83VMbS98qc/eJt2pXCJ6tRdjeIgmTRnGQx3goQaDIWGEDXKfqnbDzkt2gsJz8FTXgLDIauCyD+uHEgQ9u1JFCBcUlQ/N+bP5UYoJTwHWtSG9sqvt80Ck9Hs10VYTHr8qV+qMASsaAeFUamTvk7VTnS1q0fHkvUe/IY/5eEF3Tr1OvZf40pYPIvJpVY5zJu6E03ALOVCzgyvcfbsiqaLk/xkwY53qWsl1fEgKqOqebQxZftVKNi/UyAK6AyooEFdOXjDZw5dvLcwsn1qWFGLXxssEVx2E2H6pb8Akq0rOiJHDLHW6IMBIfbvWtnl9ZE6BxE5IRhu9KgBBHhfn3jxURvacBOIdTkIHiB67UeZ0JqdtuZ6AX24AT0f5rpQmVIGySKRCcbvh1j4c8RGLP+ZBSK8yWU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
